# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ndebiesm <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/29 13:44:33 by ndebiesm          #+#    #+#              #
#    Updated: 2019/10/29 13:44:38 by ndebiesm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME  = libft.a

SRCS 	=	ft_atoi.c\
		ft_isalpha.c\
		ft_itoa.c\
		ft_memcpy.c\
		ft_strchr.c\
		ft_strlcpy.c\
		ft_strnstr.c\
		ft_tolower.c\
		ft_bzero.c\
		ft_isascii.c\
		ft_memccpy.c\
		ft_memmove.c\
		ft_strdup.c\
		ft_strlen.c\
		ft_strrchr.c\
		ft_toupper.c\
		ft_calloc.c\
		ft_isdigit.c\
		ft_memchr.c\
		ft_memset.c\
		ft_strjoin.c\
		ft_strtrim.c\
		ft_isalnum.c\
		ft_isprint.c\
		ft_memcmp.c\
		ft_split.c\
		ft_strlcat.c\
		ft_strncmp.c\
		ft_substr.c\
		ft_strmapi.c\
		ft_putchar_fd.c\
		ft_putendl_fd.c\
		ft_putnbr_fd.c\
		ft_putstr_fd.c\

BONUS		= ft_lstadd_back_bonus.c\
				  ft_lstadd_front_bonus.c\
				  ft_lstclear_bonus.c\
				  ft_lstdelone_bonus.c\
				  ft_lstiter_bonus.c\
				  ft_lstlast_bonus.c\
				  ft_lstnew_bonus.c\
				  ft_lstsize_bonus.c\
				  ft_lstmap_bonus.c\

FLAGS		=	-Wall -Wextra -Werror

CC			=	gcc

RM			=	rm -f

all:			.c.o $(NAME)

.c.o:
	$(CC) $(FLAGS) -c $(SRCS)

$(NAME): 	.c.o
		ar rc $(NAME) *.o

clean:
	$(RM) *.o

fclean:		clean
		$(RM) $(NAME)

re:		fclean all

bonus:
	$(CC) $(FLAGS) -c $(BONUS)
	ar rc $(NAME) *.o

.PHONY:			all .c.o $(NAME) clean cleanf re bonus
